# Multi job config

jobs:
  fmt:
    function: common/dev_actions/fmt:main
    targets:
      - docker_droplet

  clean:
    function: prod_actions/clean:main
    context:
      clean_dirs:
        - build
        - dist
        - docker_droplet.egg-info

  pypi-upload:
    function: dev_actions/pypi_upload:main
    context:
      release_type: patch
      twine_username: joellefkowitz

projects:
  docker_droplet:
    path: ../docker_droplet
