jobs:
  fmt:
    command: black . --exclude venv
    targets:
      - all

  yenv:
    function: yenv:main
    context:
      yenv-file: ../environment.yml
      env-targets:
        - docker-droplet

  clean:
    function: clean:main
    context:
      clean_dirs:
        - build
        - dist
        - docker-droplet.egg-info

  pypi-upload:
    function: pypi_upload:main
    context:
      release_type: patch
      twine_username: joellefkowitz


projects:
  docker-droplet:
    path: ../docker-droplet

routines:
  release:
    - fmt
    - clean
    - pypi_upload
