
- name: Install python3
  raw: 'sudo apt-get -y install python3'

- name: Install pip
  apt: update_cache=yes name=python3-pip state=latest

- name: Install setuptools
  pip:
    name: setuptools
    executable: pip3